# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-07-18 21:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojo_ninjas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dojo',
            name='desc',
            field=models.TextField(default='desc', max_length=255),
        ),
    ]
